apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: example-2-pr
spec:
  serviceAccountName: buildpacks-service-account
  pipelineRef:
    name: example-2-pipeline
  params:
    - name: git-url
      value: "https://github.com/shengyu/hello"
    - name: git-revision
      value: "main"
    - name: git-subdir
      value: ""
    - name: app-image
      value: "usungu/hello:v0.0.3"
    - name: builder-image
      value: "gcr.io/buildpacks/builder:v1"
    - name: yaml-path
      value: "deployment.yaml"
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: results-ws-pvc
    - name: cache-ws
      subPath: cache
      persistentVolumeClaim:
        claimName: results-ws-pvc