apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: github-repo
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/shengyu/tekton-demo.git
    - name: revision
      value: master