apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-apply
spec:
  params:
    - name: yaml-path
      description: "The path to the yaml file to deploy within the git source"
    - name: app-image
      description: "Url of image repository"
  workspaces:
    - name: source
      description: Directory where application source is located.
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;__IMAGE__;$(params.app-image);g"
        - "$(workspaces.source.path)/$(params.yaml-path)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(workspaces.source.path)/$(params.yaml-path)"